const PDFDocument = require('pdfkit');

// Generate a simple certificate PDF as a Buffer
// params: { recipientName, eventName, eventDate, location, registrationId }
module.exports = function generateCertificate(params = {}) {
  const {
    recipientName = 'Participant',
    eventName = 'Event',
    eventDate = '',
    location = '',
    registrationId = '',
  } = params;

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks = [];

  doc.on('data', (chunk) => chunks.push(chunk));

  // Styling
  doc.rect(45, 45, doc.page.width - 90, doc.page.height - 90).stroke('#14b8a6');

  doc
    .fontSize(26)
    .fillColor('#111827')
    .text('Certificate of Participation', { align: 'center' })
    .moveDown(1.2);

  doc
    .fontSize(14)
    .fillColor('#374151')
    .text(
      'This is to certify that',
      { align: 'center' }
    )
    .moveDown(0.5);

  doc
    .fontSize(22)
    .fillColor('#111827')
    .text(recipientName, { align: 'center' })
    .moveDown(0.8);

  doc
    .fontSize(14)
    .fillColor('#374151')
    .text('has successfully registered and participated in', { align: 'center' })
    .moveDown(0.5);

  doc
    .fontSize(18)
    .fillColor('#111827')
    .text(eventName, { align: 'center' })
    .moveDown(1);

  const metaLines = [];
  if (eventDate) metaLines.push(`Date: ${eventDate}`);
  if (location) metaLines.push(`Location: ${location}`);
  if (registrationId) metaLines.push(`Registration ID: ${registrationId}`);

  if (metaLines.length) {
    doc
      .fontSize(11)
      .fillColor('#6B7280')
      .text(metaLines.join('  •  '), { align: 'center' })
      .moveDown(2);
  }

  // Signature line
  const y = doc.y + 60;
  doc
    .moveTo(100, y)
    .lineTo(260, y)
    .stroke('#9CA3AF');
  doc
    .fontSize(10)
    .fillColor('#6B7280')
    .text('Event Coordinator', 100, y + 6, { width: 160, align: 'center' });

  // Footer
  doc
    .fontSize(9)
    .fillColor('#9CA3AF')
    .text('Generated by Event Portal', 0, doc.page.height - 60, { align: 'center' });

  doc.end();

  return new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err) => reject(err));
  });
};
